# Generated by Django 3.2.3 on 2021-07-02 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_pagar', models.CharField(choices=[('AG', 'Água'), ('LU', 'Luz'), ('TE', 'Telefone'), ('IN', 'Internet'), ('AL', 'Alimentação'), ('HO', 'Hobby'), ('OT', 'Outros')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_receber', models.CharField(choices=[('SE', 'Serviço prestado'), ('SA', 'Salário'), ('VE', 'Vendas')], default='SE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('DI', 'Dinheiro'), ('BB', 'Boleto'), ('CC', 'Crédito'), ('CD', 'Débito'), ('DB', 'Depósito'), ('TR', 'Tranferência')], default='DI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(choices=[('P', 'Pago'), ('N', 'A pagar')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(choices=[('R', 'Recebido'), ('N', 'Não recebido')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expectativa', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(max_length=300, null=True)),
                ('classificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.classificacaoreceber')),
                ('formapagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.formapagamento')),
                ('situacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.situacaoreceber')),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(default=datetime.datetime(2021, 7, 2, 4, 3, 30, 881743))),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(max_length=300, null=True)),
                ('classificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.classificacaopagar')),
                ('formapagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.formapagamento')),
                ('situacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.situacaopagar')),
            ],
        ),
    ]
