# Generated by Django 3.2.3 on 2021-07-03 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='OT', max_length=2)),
                ('descricao', models.CharField(default='Outros', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='SA', max_length=2)),
                ('descricao', models.CharField(default='Salário', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='DI', max_length=2)),
                ('descricao', models.CharField(default='Dinheiro', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expectativa', models.DateField()),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField(max_length=300, null=True)),
                ('situacao', models.CharField(choices=[('R', 'Recebido'), ('N', 'Não recebido')], default='N', max_length=1)),
                ('classificacao', models.ForeignKey(default='SA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.classificacaoreceber')),
                ('formapagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField(max_length=300, null=True)),
                ('situacao', models.CharField(choices=[('S', 'Pago'), ('N', 'A pagar')], default='N', max_length=1)),
                ('classificacao', models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.classificacaopagar')),
                ('formapagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.formapagamento')),
            ],
        ),
    ]
