# Generated by Django 3.2.3 on 2021-07-03 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacaopagar',
            name='classificacao_pagar',
        ),
        migrations.RemoveField(
            model_name='classificacaoreceber',
            name='classificacao_receber',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='classificacaopagar',
            name='descricao',
            field=models.CharField(default='Outros', max_length=20),
        ),
        migrations.AddField(
            model_name='classificacaopagar',
            name='sigla',
            field=models.CharField(default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='classificacaoreceber',
            name='descricao',
            field=models.CharField(default='Salário', max_length=20),
        ),
        migrations.AddField(
            model_name='classificacaoreceber',
            name='sigla',
            field=models.CharField(default='SA', max_length=2),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='descricao',
            field=models.CharField(default='Dinheiro', max_length=20),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='sigla',
            field=models.CharField(default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='data_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data_recebimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='situacaopagar',
            name='escolha',
            field=models.CharField(choices=[('S', 'Pago'), ('N', 'A pagar')], default='N', max_length=1),
        ),
    ]
