# Generated by Django 3.2.3 on 2021-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data_recebimento',
            field=models.DateField(null=True),
        ),
    ]
