# Generated by Django 3.2.3 on 2021-07-05 23:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20210703_2352'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classificacaopagar',
            managers=[
                ('classif_pagar_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classificacaoreceber',
            managers=[
                ('classif_receber_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
