# Generated by Django 3.2.3 on 2021-07-06 06:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
			('contas', '0010_auto_20210705_2205'),
			]

	operations = [
			migrations.AlterModelManagers(
					name='formapagamento',
					managers=[
							('pagamentos_objects', django.db.models.manager.Manager()),
							],
					),
			]
